### ISSUE TITLE
Create ButtonsGrid Component

### ISSUE THREAD

**Issue by manico** [nsftx/nsoft-components#11]
This is a component that is a grid of buttons. This component holds no logic about minimum and maximum selection as that will be handled by upper components.

Current implementation:
<img width="404" alt="Screenshot 2019-05-06 at 11 47 17" src="https://user-images.githubusercontent.com/22288642/57218143-dd7a6480-6ff4-11e9-8f5d-67dd1cd80012.png">

Design:
https://app.zeplin.io/project/58e24f0b8c7222d370f8c40c/screen/5cc463da9163353db1c37111

Props:
- value (hold selection as array of objects)
- numberOfRows
- numberOfColumns
- buttonList
   - key
   - hex

**Comment by manico** [comment]
Branch `feature/buttonGrid`.

**Comment by dika-pro** [comment]
After discussion we decided that this component has min and max validation and it emits error if next selection is out of range.

**Comment by dika-pro** [comment]
Done in #60
