### ISSUE TITLE
Deploy as library to npm repo.

### ISSUE THREAD

**Issue by aldinezi** [nsftx/nsoft-components#20]
Can we have per component exports as library, so we can install and use specific components we need in our projects?

**Comment by manico** [comment]
Just tag people you need in discussion.
I did not notice this at all. :)

Do we have an example how to create packages, group them by which logic?

**Comment by aldinezi** [comment]
I am not sure about grouping. I was thinking about named exports of each component, so the end user can import any component he wants. 
In the case of keyboard, we just need to export it's plugin for use in Vue projects.

**Comment by manico** [comment]
Sure. Just create PR to see where you're going. :)

**Comment by aldinezi** [comment]
Resolved in #24 and #25 
https://www.npmjs.com/package/@nsoft/nsoft-components
