### ISSUE TITLE
Create BingoGridButton

### ISSUE THREAD

**Issue by dika-pro** [nsftx/nsoft-components#52]
Create `BingoButton` that will extend `Button` and it has specific bingo states. See under **Selected Flat** for states(https://app.zeplin.io/project/58e24f0b8c7222d370f8c40c/screen/5cc463da9163353db1c37111)

**Comment by t3o79** [comment]
I will add this into a priority of iterations_19

**Comment by t3o79** [comment]
I have some questions about this task.

- I need to create a button for a square/circle and selected flat/gradient?
- I will get an active state from a parent? I suppose that will be the case.

**Comment by dika-pro** [comment]
> I have some questions about this task.
> 
> * I need to create a button for a square/circle and selected flat/gradient?
Only circle now.
> * I will get an active state from a parent? I suppose that will be the case.
That's right.

**Comment by dika-pro** [comment]
Feel free to close issue :100:
