### ISSUE TITLE
Create input component

### ISSUE THREAD

**Issue by dika-pro** [nsftx/nsoft-components#74]
Create `Input` component.

Styleguide: https://app.zeplin.io/project/578c9f9a1796cfe01a63d4e1/screen/5e15ba60b7ed338440dbe669

Props:
 - validate-on-blur (boolean) -> run validation on each keypress and also on blur if this prop is set to false
 - rules (array) -> rules as functions. Each function must return either false (input is valid) or true/string if invalid
 - error-messages (Array) -> array of messages to show. This can be used instead of rules (e.g. there is an async validator)
- error (boolean) -> Puts the input in a manual error state
- success (boolean) -> Puts the input in a manual success state

**Comment by t3o79** [comment]
Here we have very little info about input validations.

We have a message element,  but we don't know when this text will be shown? On start? If some "onkey." event fails? Or when we go out from input?

Then what type of validations will we have? Only numbers, only letters ...?

If we go with validation inside the input, We can put props with validation name and with that we can handle validation on input.
If input will be only a dummy element, then handling will be on the app parent side. And we will get the message from the parent and we will show it (error or success).

Please some info about this

**Comment by manico** [comment]
- Helper text is always visible and it is set as a prop
- Helper text changes to error message on validation fail
- Validation should be passed as an prop object to input component

It would be best to pass validation library (as prop) from parent application.
This is what I would suggest.

**Comment by t3o79** [comment]
And it would be good to leave what type of validation will be available.

- Only Numbers
- Only numbers with dot
- Only numbers with comma
- Only Letters

And validation will be on every keypress or when we blur input?

**Comment by aldinezi** [comment]
Regarding the question when should the input be validated, from our experience there are two major cases when we validate input, while typing and on exiting input. In some rare non-vue scenarios there are some on submit validations too, but I regard it retrograde in modern UI/UX and it should not be concerned. 
That said, it would be good to support different validation events as prop.

I agree that validation should be passed as prop while at the same time component could have it's own basic validations.

**Comment by t3o79** [comment]
Continue chat inside slack channel

**Comment by t3o79** [comment]
Validation is left inside the input component. A parent must add rules (as an array) props.

- the value will be as props from parent
- Rules must be function, each function, it is invalid, will return a string and the input component will store it inside locale array (error message).
- Validation will be on key or blur depending on validateOnBlur props (default is false). 
- helper message is props and depending on error-message, helper or error will be shown
- label title (i called it like that, we can change it) is required
- the icon can be set as a wish (default is loop magnifier)
- component type can be box or line (default is a box)
- disable as props from the parent (default will be false)

 Helper message, error messages, label title -  must be properly translated

**Comment by dika-pro** [comment]
All fine. Additionally we agreed to add `success` and `error` states so parent can set manually state of a input.
