### ISSUE TITLE
Create ColorCheckboxList Component

### ISSUE THREAD

**Issue by manico** [nsftx/nsoft-components#9]
This is a list of `ColorCheckbox` components. Additional prop is list of colors (hex strings).

Current implementation:
<img width="392" alt="Screenshot 2019-05-06 at 11 37 07" src="https://user-images.githubusercontent.com/22288642/57217587-5082db80-6ff3-11e9-90c7-f7053441bc3c.png">

Rules:
- Only one item can be selected.

Design:
https://app.zeplin.io/project/58e24f0b8c7222d370f8c40c/screen/5cc463da9163353db1c37111

**Comment by dika-pro** [comment]
Additionally it must emit selected value.

**Comment by dika-pro** [comment]
One more thing @itsadesigning, every click on button should toggle state.
